"""Categorical string-to-index mappings extracted from training partition."""

CATEGORICAL_MAPPINGS = {
  "department": {
    "Accounting": 24,
    "Accounts Payable": 29,
    "Accounts Receiveable": 25,
    "Admin Offices": 23,
    "Analytics": 5,
    "Audit": 28,
    "Bakery": 10,
    "Compensation": 36,
    "Customer Service": 7,
    "Dairy": 8,
    "Employee Records": 32,
    "Executive": 34,
    "Executive Office": 37,
    "Finance": 12,
    "HR": 13,
    "HR Technology": 30,
    "Human Resources": 18,
    "IT/IS": 19,
    "Information Technology": 33,
    "Investment": 35,
    "Labor Relations": 31,
    "Legal": 16,
    "Meats": 9,
    "Operations": 2,
    "Processed Foods": 14,
    "Procurement": 3,
    "Produce": 11,
    "Production": 15,
    "R&D": 17,
    "Recruitment": 27,
    "Research & Development": 1,
    "Sales": 6,
    "Sales & Marketing": 0,
    "Software Engineering": 22,
    "Store Management": 21,
    "Technology": 4,
    "Training": 26,
    "nan": 20
  },
  "job_level": {
    "Entry": 1,
    "Lead": 4,
    "Manager": 2,
    "Mid": 0,
    "Senior": 3
  },
  "role": {
    "AVP": 142,
    "Account Executive": 28,
    "Account Manager": 29,
    "Accountant": 71,
    "Actuarial Analyst": 286,
    "Administrative": 122,
    "Administrative Assistant": 42,
    "Administrator": 159,
    "Advisor": 278,
    "Advisory Associate": 214,
    "Advisory Manager": 127,
    "Advisory Software Engineer": 208,
    "Analyst": 9,
    "Anonymous": 132,
    "Anonymous Employee": 0,
    "Apple At Home Advisor": 263,
    "Apple Genius": 255,
    "Applications Developer": 43,
    "Applications Engineer": 186,
    "Architect": 231,
    "Assistant": 182,
    "Assistant Manager": 21,
    "Assistant Store Manager": 270,
    "Assistant Vice President": 48,
    "Associate": 7,
    "Associate Analyst": 254,
    "Associate Consultant": 38,
    "Associate Director": 81,
    "Associate Partner": 226,
    "Associate Software Engineer": 187,
    "Associate Systems Engineer": 125,
    "Assurance Associate": 102,
    "Audit Assistant": 126,
    "Audit Associate": 25,
    "Audit Manager": 73,
    "Audit Senior": 40,
    "Audit Senior Associate": 52,
    "Audit Staff": 184,
    "Auditor": 64,
    "Bank Teller": 166,
    "Bartender": 224,
    "Branch Manager": 183,
    "Business Analyst": 22,
    "Business Development": 237,
    "Business Development Consultant": 204,
    "Business Development Manager": 135,
    "Business Development Representative": 178,
    "Business Manager": 162,
    "Business Technology Analyst": 82,
    "Cabin Crew": 157,
    "Cashier": 12,
    "Checkout Operator": 238,
    "Chef": 181,
    "Cleaner": 217,
    "Consultant": 5,
    "Cook": 62,
    "Crew": 168,
    "Crew Member": 10,
    "Crew Member/Grill Cook": 154,
    "Crew Trainer": 61,
    "Current Employee - Anonymous Employee": 2,
    "Current Employee - Fulfillment Associate": 216,
    "Current Employee - Program Manager": 149,
    "Current Employee - Senior Program Manager": 190,
    "Current Employee - Senior Software Engineer": 175,
    "Current Employee - Software Development Engineer": 91,
    "Current Employee - Software Development Engineer II": 195,
    "Current Employee - Software Engineer": 68,
    "Current Employee - Specialist": 141,
    "Current Employee - Warehouse Associate": 240,
    "Customer Advisor": 83,
    "Customer Assistant": 18,
    "Customer Assistant Tesco": 171,
    "Customer Service": 30,
    "Customer Service Advisor": 78,
    "Customer Service Agent": 223,
    "Customer Service Assistant": 54,
    "Customer Service Associate": 138,
    "Customer Service Executive": 257,
    "Customer Service Representative": 23,
    "Customer Service Specialist": 202,
    "Customer Success Manager": 207,
    "Data Analyst": 58,
    "Data Scientist": 69,
    "Delivery Driver": 51,
    "Department Manager": 167,
    "Deputy Manager": 119,
    "Designer": 279,
    "Developer": 130,
    "Devops Engineer": 271,
    "Director": 20,
    "Driver": 287,
    "Engagement Manager": 139,
    "Engineer": 66,
    "Executive": 129,
    "Executive Assistant": 57,
    "Executive Director": 114,
    "Experienced Audit Associate": 244,
    "Family Room Specialist": 259,
    "Finance": 155,
    "Finance Analyst": 228,
    "Finance Manager": 95,
    "Financial Advisor": 163,
    "Financial Analyst": 32,
    "Former Employee - Anonymous Employee": 6,
    "Former Employee - Software Development Engineer": 258,
    "Former Employee - Software Engineer": 173,
    "Former Employee - Specialist": 191,
    "Former Employee - Warehouse Associate": 268,
    "Front Desk Agent": 67,
    "Front Desk Receptionist": 143,
    "Fry Cook": 277,
    "General Assistant": 124,
    "General Manager": 70,
    "Genius": 206,
    "Graduate": 250,
    "Graduate Student": 242,
    "Healthcare Representative": 115,
    "Housekeeper": 116,
    "Human Resources": 86,
    "Human Resources Business Partner": 251,
    "Human Resources Manager": 123,
    "IT Analyst": 246,
    "IT Consultant": 193,
    "IT Manager": 150,
    "IT Project Manager": 153,
    "IT Specialist": 87,
    "Inside Sales Representative": 252,
    "Intern": 27,
    "Internship": 177,
    "Investment Banking Analyst": 100,
    "Laboratory Technician": 56,
    "Lecturer": 266,
    "Line Cook": 111,
    "Mac Genius": 235,
    "Mac Specialist (Apple Store)": 222,
    "Management": 274,
    "Management Consultant": 146,
    "Manager": 3,
    "Managing Consultant": 110,
    "Managing Director": 145,
    "Manufacturing Director": 108,
    "Marketing": 94,
    "Marketing Manager": 55,
    "McDonalds Cashier": 234,
    "McDonalds Crew Trainer": 152,
    "Mcdonalds Crew Member": 41,
    "Member Of Technical Staff": 205,
    "Network Engineer": 192,
    "Night Auditor": 275,
    "Operations": 188,
    "Operations Analyst": 104,
    "Operations Manager": 75,
    "Operations Specialist": 284,
    "Operations Supervisor": 221,
    "Optical Assistant": 239,
    "Part": 198,
    "Partner": 131,
    "Personal Assistant": 243,
    "Personal Banker": 92,
    "PhD Student": 65,
    "Postdoctoral Research Associate": 179,
    "Principal": 170,
    "Principal Consultant": 109,
    "Principal Software Engineer": 136,
    "Product Manager": 46,
    "Product Marketing Manager": 273,
    "Product Specialist": 249,
    "Production Technician I": 194,
    "Program Manager": 44,
    "Programmer Analyst": 147,
    "Project Coordinator": 212,
    "Project Leader": 229,
    "Project Manager": 19,
    "Receptionist": 96,
    "Recruiter": 74,
    "Recruitment Consultant": 85,
    "Registered Nurse": 269,
    "Relationship Banker": 262,
    "Relationship Manager": 113,
    "Research Analyst": 220,
    "Research Assistant": 97,
    "Research Associate": 84,
    "Research Director": 196,
    "Research Scientist": 49,
    "Researcher": 201,
    "Retail Assistant": 50,
    "Retail Sales Assistant": 133,
    "Retail Sales Associate": 90,
    "Risk Analyst": 165,
    "SAP Consultant": 247,
    "Sales": 33,
    "Sales Advisor": 45,
    "Sales Assistant": 15,
    "Sales Associate": 24,
    "Sales Associate/Cashier": 107,
    "Sales Consultant": 80,
    "Sales Director": 272,
    "Sales Executive": 31,
    "Sales Manager": 47,
    "Sales Representative": 39,
    "Sales Specialist": 121,
    "Security Officer": 288,
    "Senior": 128,
    "Senior Account Executive": 117,
    "Senior Account Manager": 260,
    "Senior Accountant": 93,
    "Senior Analyst": 37,
    "Senior Applications Developer": 256,
    "Senior Associate": 11,
    "Senior Associate Consultant": 236,
    "Senior Audit Associate": 248,
    "Senior Auditor": 88,
    "Senior Business Analyst": 106,
    "Senior Consultant": 8,
    "Senior Developer": 264,
    "Senior Director": 99,
    "Senior Engineer": 169,
    "Senior Executive": 199,
    "Senior Financial Analyst": 120,
    "Senior Manager": 17,
    "Senior Managing Consultant": 265,
    "Senior Marketing Manager": 203,
    "Senior Member of Technical Staff": 200,
    "Senior Product Manager": 134,
    "Senior Program Manager": 89,
    "Senior Project Manager": 76,
    "Senior Software Developer": 118,
    "Senior Software Development Engineer": 245,
    "Senior Software Engineer": 16,
    "Senior Systems Engineer": 164,
    "Senior Vice President": 180,
    "Server": 105,
    "Server/Waiter": 213,
    "Service Delivery Manager": 261,
    "Shift Leader": 276,
    "Shift Manager": 53,
    "Shop Assistant": 158,
    "Shop Floor Assistant": 283,
    "Software Developer": 26,
    "Software Development Engineer": 77,
    "Software Development Engineer II": 225,
    "Software Development Engineer In Test (SDET)": 197,
    "Software Engineer": 4,
    "Software Engineer II": 209,
    "Solutions Architect": 144,
    "Specialist": 34,
    "Staff": 230,
    "Staff Accountant": 103,
    "Staff Consultant": 232,
    "Staff Software Engineer": 160,
    "Store Assistant": 161,
    "Store Manager": 72,
    "Student": 35,
    "Student Ambassador": 233,
    "Supermarket Assistant": 156,
    "Supervisor": 59,
    "Support Engineer": 189,
    "Support Worker": 211,
    "Systems Administrator": 172,
    "Systems Analyst": 215,
    "Systems Engineer": 79,
    "Tax Analyst": 219,
    "Tax Associate": 63,
    "Tax Consultant": 151,
    "Tax Manager": 112,
    "Tax Senior": 176,
    "Tax Senior Associate": 148,
    "Team Lead": 140,
    "Team Leader": 36,
    "Team Manager": 137,
    "Team Member": 60,
    "Technical Consultant": 282,
    "Technical Lead": 185,
    "Technical Specialist": 101,
    "Technical Support Engineer": 98,
    "Technician": 253,
    "Technology Analyst": 174,
    "Technology Consultant": 267,
    "Teller": 241,
    "Trading Assistant": 281,
    "Unknown": 1,
    "User Experience Designer": 218,
    "Vice President": 13,
    "Waitress": 210,
    "Waitrose Supermarket Assistant": 285,
    "Warehouse Operative": 280,
    "Warehouse Worker": 227,
    "nan": 14
  },
  "communication_patterns": {
    "Exhibits communication style typical of a 9-to-5Clockwatcher persona.": 9,
    "Exhibits communication style typical of a AmbitiousClimber persona.": 7,
    "Exhibits communication style typical of a BurntOutStar persona.": 8,
    "Exhibits communication style typical of a ChangeResistor persona.": 10,
    "Exhibits communication style typical of a CorporateNavigator persona.": 1,
    "Exhibits communication style typical of a NewEnthusiast persona.": 3,
    "Exhibits communication style typical of a OverachievingSprinter persona.": 6,
    "Exhibits communication style typical of a QuietAchiever persona.": 11,
    "Exhibits communication style typical of a SeasonedExpert persona.": 5,
    "Exhibits communication style typical of a SocialCatalyst persona.": 4,
    "Exhibits communication style typical of a SteadyEddy persona.": 2,
    "Exhibits communication style typical of a StrugglingLearner persona.": 0
  },
  "persona_name": {
    "9-to-5Clockwatcher": 9,
    "AmbitiousClimber": 7,
    "BurntOutStar": 8,
    "ChangeResistor": 10,
    "CorporateNavigator": 1,
    "NewEnthusiast": 3,
    "OverachievingSprinter": 6,
    "QuietAchiever": 11,
    "SeasonedExpert": 5,
    "SocialCatalyst": 4,
    "SteadyEddy": 2,
    "StrugglingLearner": 0
  }
}
