services:
  - type: web
    name: sentinel-workforce-risk
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: standard
    region: oregon
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: "production"
      - key: ARTIFACTS_DIR
        value: "/app/artifacts"
      - key: HF_MODEL_REPO_ID
        value: "ParminderzHuggingFace/sentinel-workforce-risk-models"
      - key: TORCH_NUM_THREADS
        value: "1"
      - key: TORCH_NUM_INTEROP_THREADS
        value: "1"
