import { EmployeePredictionRequest } from '../types/api';

export const SAMPLE_EMPLOYEES: EmployeePredictionRequest[] = [
  {
    employee_id: "EMP-1001",
    department: "Engineering",
    job_level: "Senior",
    role: "Senior Software Engineer",
    communication_patterns: "Collaborative",
    persona_name: "Technical Pillar",
    tenure_months: 38.0,
    salary: 145000,
    performance_score: 0.92,
    satisfaction_score: 0.88,
    workload_score: 0.42,
    team_sentiment: 0.86,
    project_completion_rate: 0.95,
    overtime_hours: 2.0,
    training_participation: 0.80,
    collaboration_score: 0.85,
    email_sentiment: 0.82,
    slack_activity: 0.75,
    meeting_participation: 0.70,
    goal_achievement_rate: 0.90,
    stress_level: 0.25,
    role_complexity_score: 0.80,
    career_progression_score: 0.75,
    technical_skills: ["Python", "PyTorch", "Distributed Systems", "PostgreSQL"],
    soft_skills: ["Mentorship", "System Design", "Agile Leadership"],
    recent_feedback: "Outstanding quarter. Clear project vision, fantastic team camaraderie, and strong executive sponsorship."
  },
  {
    employee_id: "EMP-2042",
    department: "Sales",
    job_level: "Mid",
    role: "Enterprise Account Executive",
    communication_patterns: "High Velocity",
    persona_name: "Quota Driver",
    tenure_months: 14.0,
    salary: 82000,
    performance_score: 0.65,
    satisfaction_score: 0.28,
    workload_score: 0.96,
    team_sentiment: 0.38,
    project_completion_rate: 0.62,
    overtime_hours: 24.0,
    training_participation: 0.10,
    collaboration_score: 0.40,
    email_sentiment: 0.30,
    slack_activity: 0.88,
    meeting_participation: 0.85,
    goal_achievement_rate: 0.60,
    stress_level: 0.94,
    role_complexity_score: 0.70,
    career_progression_score: 0.25,
    technical_skills: ["Salesforce", "Outreach", "Contract Negotiation"],
    soft_skills: ["Cold Calling", "Objection Handling"],
    recent_feedback: "Severe burnout from impossible quarterly quotas and 70-hour weeks. Zero recognition from leadership and toxic pressure."
  },
  {
    employee_id: "EMP-3015",
    department: "Product",
    job_level: "Lead",
    role: "Staff Product Designer",
    communication_patterns: "Async Focused",
    persona_name: "Strategic Innovator",
    tenure_months: 48.0,
    salary: 130000,
    performance_score: 0.78,
    satisfaction_score: 0.55,
    workload_score: 0.72,
    team_sentiment: 0.65,
    project_completion_rate: 0.80,
    overtime_hours: 8.0,
    training_participation: 0.50,
    collaboration_score: 0.70,
    email_sentiment: 0.60,
    slack_activity: 0.60,
    meeting_participation: 0.75,
    goal_achievement_rate: 0.75,
    stress_level: 0.62,
    role_complexity_score: 0.85,
    career_progression_score: 0.40,
    technical_skills: ["Figma", "User Research", "Design Systems"],
    soft_skills: ["Cross-functional Alignment", "Storytelling"],
    recent_feedback: "Enjoy the creative scope but experiencing ambiguity around roadmaps and plateauing compensation trajectory."
  },
  {
    employee_id: "EMP-4089",
    department: "Customer Support",
    job_level: "Entry",
    role: "Support Specialist",
    communication_patterns: "High Queue",
    persona_name: "Frontline Resolver",
    tenure_months: 8.0,
    salary: 52000,
    performance_score: 0.82,
    satisfaction_score: 0.45,
    workload_score: 0.88,
    team_sentiment: 0.58,
    project_completion_rate: 0.85,
    overtime_hours: 14.0,
    training_participation: 0.35,
    collaboration_score: 0.62,
    email_sentiment: 0.48,
    slack_activity: 0.70,
    meeting_participation: 0.50,
    goal_achievement_rate: 0.80,
    stress_level: 0.82,
    role_complexity_score: 0.45,
    career_progression_score: 0.30,
    technical_skills: ["Zendesk", "Jira", "Technical Troubleshooting"],
    soft_skills: ["Empathy", "De-escalation"],
    recent_feedback: "Ticket volume has doubled with no headcount additions. Difficult to maintain quality when constantly rushed."
  },
  {
    employee_id: "EMP-5120",
    department: "Operations",
    job_level: "Manager",
    role: "Operations Manager",
    communication_patterns: "Orchestrator",
    persona_name: "Operational Leader",
    tenure_months: 60.0,
    salary: 118000,
    performance_score: 0.88,
    satisfaction_score: 0.82,
    workload_score: 0.58,
    team_sentiment: 0.84,
    project_completion_rate: 0.90,
    overtime_hours: 4.0,
    training_participation: 0.70,
    collaboration_score: 0.90,
    email_sentiment: 0.78,
    slack_activity: 0.80,
    meeting_participation: 0.85,
    goal_achievement_rate: 0.88,
    stress_level: 0.45,
    role_complexity_score: 0.75,
    career_progression_score: 0.70,
    technical_skills: ["ERP Systems", "Supply Chain", "Budgeting"],
    soft_skills: ["Vendor Management", "Conflict Resolution", "Coaching"],
    recent_feedback: "Smooth quarterly execution across supply chain logistics. Team is well-staffed and operational targets were exceeded."
  }
];
