import { EmployeePredictionRequest } from '../types/api';

export const SAMPLE_EMPLOYEES: EmployeePredictionRequest[] = [
  {
    "employee_id": "EMP-1001",
    "department": "Software Engineering",
    "job_level": "Senior",
    "role": "Software Engineer",
    "communication_patterns": "Exhibits communication style typical of a SystemsArchitect persona.",
    "persona_name": "Elena Rostova",
    "tenure_months": 56.0,
    "salary": 153268.0,
    "performance_score": 0.92,
    "satisfaction_score": 0.91,
    "workload_score": 0.44,
    "team_sentiment": 0.88,
    "project_completion_rate": 0.93,
    "overtime_hours": 3.3,
    "training_participation": 0.84,
    "collaboration_score": 0.86,
    "email_sentiment": 0.9,
    "slack_activity": 0.74,
    "meeting_participation": 0.56,
    "goal_achievement_rate": 0.92,
    "stress_level": 0.16,
    "role_complexity_score": 0.59,
    "career_progression_score": 0.86,
    "technical_skills": [
      "Software Engineering Core",
      "Software Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Great culture, highly collaborative team, and strong support from management on career growth."
  },
  {
    "employee_id": "EMP-1002",
    "department": "Technology",
    "job_level": "Lead",
    "role": "DevOps Engineer",
    "communication_patterns": "Exhibits communication style typical of a CloudInfrastructure persona.",
    "persona_name": "Marcus Vance",
    "tenure_months": 49.0,
    "salary": 162708.0,
    "performance_score": 0.9,
    "satisfaction_score": 0.89,
    "workload_score": 0.4,
    "team_sentiment": 0.86,
    "project_completion_rate": 0.91,
    "overtime_hours": 2.5,
    "training_participation": 0.8,
    "collaboration_score": 0.83,
    "email_sentiment": 0.88,
    "slack_activity": 0.7,
    "meeting_participation": 0.53,
    "goal_achievement_rate": 0.9,
    "stress_level": 0.13,
    "role_complexity_score": 0.55,
    "career_progression_score": 0.83,
    "technical_skills": [
      "Technology Core",
      "DevOps Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Very balanced workload and exciting technical challenges. Leadership respects work-life boundaries."
  },
  {
    "employee_id": "EMP-1003",
    "department": "Analytics",
    "job_level": "Mid",
    "role": "Data Scientist",
    "communication_patterns": "Exhibits communication style typical of a PredictiveModeling persona.",
    "persona_name": "Sarah Chen",
    "tenure_months": 52.0,
    "salary": 157173.0,
    "performance_score": 0.91,
    "satisfaction_score": 0.89,
    "workload_score": 0.41,
    "team_sentiment": 0.87,
    "project_completion_rate": 0.91,
    "overtime_hours": 2.6,
    "training_participation": 0.81,
    "collaboration_score": 0.84,
    "email_sentiment": 0.88,
    "slack_activity": 0.71,
    "meeting_participation": 0.53,
    "goal_achievement_rate": 0.91,
    "stress_level": 0.14,
    "role_complexity_score": 0.55,
    "career_progression_score": 0.84,
    "technical_skills": [
      "Analytics Core",
      "Data Scientist Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Excellent compensation, modern toolchain, and transparent communication across all executive channels."
  },
  {
    "employee_id": "EMP-1004",
    "department": "Software Engineering",
    "job_level": "Mid",
    "role": "Software Engineer",
    "communication_patterns": "Exhibits communication style typical of a Frontend&UI persona.",
    "persona_name": "David Kim",
    "tenure_months": 54.0,
    "salary": 156530.0,
    "performance_score": 0.92,
    "satisfaction_score": 0.91,
    "workload_score": 0.44,
    "team_sentiment": 0.88,
    "project_completion_rate": 0.93,
    "overtime_hours": 3.3,
    "training_participation": 0.84,
    "collaboration_score": 0.86,
    "email_sentiment": 0.9,
    "slack_activity": 0.74,
    "meeting_participation": 0.57,
    "goal_achievement_rate": 0.92,
    "stress_level": 0.16,
    "role_complexity_score": 0.59,
    "career_progression_score": 0.86,
    "technical_skills": [
      "Software Engineering Core",
      "Software Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Love the team environment and autonomy given to individual contributors. Very rewarding place to work."
  },
  {
    "employee_id": "EMP-1005",
    "department": "Research & Development",
    "job_level": "Senior",
    "role": "Research Scientist",
    "communication_patterns": "Exhibits communication style typical of a AlgorithmDesign persona.",
    "persona_name": "Priya Sharma",
    "tenure_months": 58.0,
    "salary": 158902.0,
    "performance_score": 0.98,
    "satisfaction_score": 0.97,
    "workload_score": 0.54,
    "team_sentiment": 0.95,
    "project_completion_rate": 0.99,
    "overtime_hours": 5.8,
    "training_participation": 0.94,
    "collaboration_score": 0.94,
    "email_sentiment": 0.97,
    "slack_activity": 0.84,
    "meeting_participation": 0.69,
    "goal_achievement_rate": 0.98,
    "stress_level": 0.24,
    "role_complexity_score": 0.74,
    "career_progression_score": 0.94,
    "technical_skills": [
      "Research & Development Core",
      "Research Scientist Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Strong mentorship, clear progression goals, and reasonable project deadlines without weekend fire drills."
  },
  {
    "employee_id": "EMP-1006",
    "department": "Sales",
    "job_level": "Manager",
    "role": "Sales Manager",
    "communication_patterns": "Exhibits communication style typical of a TerritoryLeadership persona.",
    "persona_name": "Michael Scott",
    "tenure_months": 47.0,
    "salary": 120683.0,
    "performance_score": 0.88,
    "satisfaction_score": 0.86,
    "workload_score": 0.36,
    "team_sentiment": 0.83,
    "project_completion_rate": 0.88,
    "overtime_hours": 1.3,
    "training_participation": 0.76,
    "collaboration_score": 0.79,
    "email_sentiment": 0.84,
    "slack_activity": 0.66,
    "meeting_participation": 0.47,
    "goal_achievement_rate": 0.88,
    "stress_level": 0.09,
    "role_complexity_score": 0.48,
    "career_progression_score": 0.79,
    "technical_skills": [
      "Sales Core",
      "Sales Manager Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Great culture, highly collaborative team, and strong support from management on career growth."
  },
  {
    "employee_id": "EMP-1007",
    "department": "Customer Service",
    "job_level": "Senior",
    "role": "Customer Service Representative",
    "communication_patterns": "Exhibits communication style typical of a ClientSuccess persona.",
    "persona_name": "Amara Okafor",
    "tenure_months": 22.0,
    "salary": 116626.0,
    "performance_score": 0.97,
    "satisfaction_score": 0.96,
    "workload_score": 0.52,
    "team_sentiment": 0.93,
    "project_completion_rate": 0.98,
    "overtime_hours": 5.4,
    "training_participation": 0.92,
    "collaboration_score": 0.93,
    "email_sentiment": 0.96,
    "slack_activity": 0.82,
    "meeting_participation": 0.67,
    "goal_achievement_rate": 0.97,
    "stress_level": 0.23,
    "role_complexity_score": 0.71,
    "career_progression_score": 0.93,
    "technical_skills": [
      "Customer Service Core",
      "Customer Service Representative Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Very balanced workload and exciting technical challenges. Leadership respects work-life boundaries."
  },
  {
    "employee_id": "EMP-1008",
    "department": "Operations",
    "job_level": "Lead",
    "role": "Operations Manager",
    "communication_patterns": "Exhibits communication style typical of a SupplyChain persona.",
    "persona_name": "Carlos Mendez",
    "tenure_months": 59.0,
    "salary": 146615.0,
    "performance_score": 0.86,
    "satisfaction_score": 0.83,
    "workload_score": 0.32,
    "team_sentiment": 0.81,
    "project_completion_rate": 0.86,
    "overtime_hours": 0.5,
    "training_participation": 0.72,
    "collaboration_score": 0.77,
    "email_sentiment": 0.81,
    "slack_activity": 0.62,
    "meeting_participation": 0.42,
    "goal_achievement_rate": 0.86,
    "stress_level": 0.07,
    "role_complexity_score": 0.43,
    "career_progression_score": 0.77,
    "technical_skills": [
      "Operations Core",
      "Operations Manager Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Excellent compensation, modern toolchain, and transparent communication across all executive channels."
  },
  {
    "employee_id": "EMP-1009",
    "department": "Sales & Marketing",
    "job_level": "Mid",
    "role": "Marketing Specialist",
    "communication_patterns": "Exhibits communication style typical of a Campaigns persona.",
    "persona_name": "Rachel Green",
    "tenure_months": 15.0,
    "salary": 155083.0,
    "performance_score": 0.96,
    "satisfaction_score": 0.96,
    "workload_score": 0.52,
    "team_sentiment": 0.93,
    "project_completion_rate": 0.97,
    "overtime_hours": 5.2,
    "training_participation": 0.92,
    "collaboration_score": 0.92,
    "email_sentiment": 0.96,
    "slack_activity": 0.82,
    "meeting_participation": 0.66,
    "goal_achievement_rate": 0.96,
    "stress_level": 0.22,
    "role_complexity_score": 0.71,
    "career_progression_score": 0.92,
    "technical_skills": [
      "Sales & Marketing Core",
      "Marketing Specialist Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Love the team environment and autonomy given to individual contributors. Very rewarding place to work."
  },
  {
    "employee_id": "EMP-1010",
    "department": "Finance",
    "job_level": "Senior",
    "role": "Financial Analyst",
    "communication_patterns": "Exhibits communication style typical of a Forecasting persona.",
    "persona_name": "James Wilson",
    "tenure_months": 40.0,
    "salary": 140934.0,
    "performance_score": 0.85,
    "satisfaction_score": 0.82,
    "workload_score": 0.3,
    "team_sentiment": 0.8,
    "project_completion_rate": 0.85,
    "overtime_hours": 0.1,
    "training_participation": 0.7,
    "collaboration_score": 0.75,
    "email_sentiment": 0.8,
    "slack_activity": 0.6,
    "meeting_participation": 0.4,
    "goal_achievement_rate": 0.85,
    "stress_level": 0.05,
    "role_complexity_score": 0.4,
    "career_progression_score": 0.75,
    "technical_skills": [
      "Finance Core",
      "Financial Analyst Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Strong mentorship, clear progression goals, and reasonable project deadlines without weekend fire drills."
  },
  {
    "employee_id": "EMP-1011",
    "department": "Human Resources",
    "job_level": "Manager",
    "role": "HR Business Partner",
    "communication_patterns": "Exhibits communication style typical of a TalentManagement persona.",
    "persona_name": "Aisha Patel",
    "tenure_months": 21.0,
    "salary": 135496.0,
    "performance_score": 0.95,
    "satisfaction_score": 0.94,
    "workload_score": 0.49,
    "team_sentiment": 0.92,
    "project_completion_rate": 0.96,
    "overtime_hours": 4.6,
    "training_participation": 0.89,
    "collaboration_score": 0.9,
    "email_sentiment": 0.94,
    "slack_activity": 0.79,
    "meeting_participation": 0.63,
    "goal_achievement_rate": 0.95,
    "stress_level": 0.2,
    "role_complexity_score": 0.67,
    "career_progression_score": 0.9,
    "technical_skills": [
      "Human Resources Core",
      "HR Business Partner Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Great culture, highly collaborative team, and strong support from management on career growth."
  },
  {
    "employee_id": "EMP-1012",
    "department": "IT/IS",
    "job_level": "Mid",
    "role": "IT Specialist",
    "communication_patterns": "Exhibits communication style typical of a NetworkInfrastructure persona.",
    "persona_name": "Daniel Lee",
    "tenure_months": 37.0,
    "salary": 95137.0,
    "performance_score": 0.87,
    "satisfaction_score": 0.85,
    "workload_score": 0.35,
    "team_sentiment": 0.83,
    "project_completion_rate": 0.88,
    "overtime_hours": 1.1,
    "training_participation": 0.75,
    "collaboration_score": 0.79,
    "email_sentiment": 0.83,
    "slack_activity": 0.65,
    "meeting_participation": 0.45,
    "goal_achievement_rate": 0.87,
    "stress_level": 0.09,
    "role_complexity_score": 0.46,
    "career_progression_score": 0.79,
    "technical_skills": [
      "IT/IS Core",
      "IT Specialist Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Very balanced workload and exciting technical challenges. Leadership respects work-life boundaries."
  },
  {
    "employee_id": "EMP-1013",
    "department": "Software Engineering",
    "job_level": "Entry",
    "role": "Junior Developer",
    "communication_patterns": "Exhibits communication style typical of a FullStack persona.",
    "persona_name": "Sophia Rodriguez",
    "tenure_months": 23.0,
    "salary": 164691.0,
    "performance_score": 0.87,
    "satisfaction_score": 0.84,
    "workload_score": 0.34,
    "team_sentiment": 0.82,
    "project_completion_rate": 0.87,
    "overtime_hours": 0.9,
    "training_participation": 0.74,
    "collaboration_score": 0.78,
    "email_sentiment": 0.83,
    "slack_activity": 0.64,
    "meeting_participation": 0.45,
    "goal_achievement_rate": 0.87,
    "stress_level": 0.08,
    "role_complexity_score": 0.45,
    "career_progression_score": 0.78,
    "technical_skills": [
      "Software Engineering Core",
      "Junior Developer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Excellent compensation, modern toolchain, and transparent communication across all executive channels."
  },
  {
    "employee_id": "EMP-1014",
    "department": "Product & Design",
    "job_level": "Senior",
    "role": "Product Manager",
    "communication_patterns": "Exhibits communication style typical of a CoreExperience persona.",
    "persona_name": "Liam O'Connor",
    "tenure_months": 30.0,
    "salary": 132280.0,
    "performance_score": 0.95,
    "satisfaction_score": 0.94,
    "workload_score": 0.49,
    "team_sentiment": 0.92,
    "project_completion_rate": 0.96,
    "overtime_hours": 4.7,
    "training_participation": 0.89,
    "collaboration_score": 0.91,
    "email_sentiment": 0.94,
    "slack_activity": 0.79,
    "meeting_participation": 0.63,
    "goal_achievement_rate": 0.95,
    "stress_level": 0.21,
    "role_complexity_score": 0.67,
    "career_progression_score": 0.91,
    "technical_skills": [
      "Product & Design Core",
      "Product Manager Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Love the team environment and autonomy given to individual contributors. Very rewarding place to work."
  },
  {
    "employee_id": "EMP-1015",
    "department": "Technology",
    "job_level": "Lead",
    "role": "Architect",
    "communication_patterns": "Exhibits communication style typical of a PlatformEngineering persona.",
    "persona_name": "Fatima Al-Mansoor",
    "tenure_months": 55.0,
    "salary": 164192.0,
    "performance_score": 0.92,
    "satisfaction_score": 0.9,
    "workload_score": 0.43,
    "team_sentiment": 0.88,
    "project_completion_rate": 0.92,
    "overtime_hours": 3.1,
    "training_participation": 0.83,
    "collaboration_score": 0.85,
    "email_sentiment": 0.89,
    "slack_activity": 0.73,
    "meeting_participation": 0.55,
    "goal_achievement_rate": 0.92,
    "stress_level": 0.15,
    "role_complexity_score": 0.58,
    "career_progression_score": 0.85,
    "technical_skills": [
      "Technology Core",
      "Architect Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Strong mentorship, clear progression goals, and reasonable project deadlines without weekend fire drills."
  },
  {
    "employee_id": "EMP-1016",
    "department": "Research & Development",
    "job_level": "Mid",
    "role": "Bioinformatics Specialist",
    "communication_patterns": "Exhibits communication style typical of a DataPipelines persona.",
    "persona_name": "Alexander Wright",
    "tenure_months": 20.0,
    "salary": 92624.0,
    "performance_score": 0.96,
    "satisfaction_score": 0.96,
    "workload_score": 0.51,
    "team_sentiment": 0.93,
    "project_completion_rate": 0.97,
    "overtime_hours": 5.1,
    "training_participation": 0.91,
    "collaboration_score": 0.92,
    "email_sentiment": 0.95,
    "slack_activity": 0.81,
    "meeting_participation": 0.65,
    "goal_achievement_rate": 0.96,
    "stress_level": 0.22,
    "role_complexity_score": 0.7,
    "career_progression_score": 0.92,
    "technical_skills": [
      "Research & Development Core",
      "Bioinformatics Specialist Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Great culture, highly collaborative team, and strong support from management on career growth."
  },
  {
    "employee_id": "EMP-1017",
    "department": "Sales",
    "job_level": "Mid",
    "role": "Account Executive",
    "communication_patterns": "Exhibits communication style typical of a EnterpriseAccounts persona.",
    "persona_name": "Chloe Bennett",
    "tenure_months": 53.0,
    "salary": 87169.0,
    "performance_score": 0.88,
    "satisfaction_score": 0.86,
    "workload_score": 0.36,
    "team_sentiment": 0.83,
    "project_completion_rate": 0.88,
    "overtime_hours": 1.3,
    "training_participation": 0.76,
    "collaboration_score": 0.79,
    "email_sentiment": 0.84,
    "slack_activity": 0.66,
    "meeting_participation": 0.47,
    "goal_achievement_rate": 0.88,
    "stress_level": 0.09,
    "role_complexity_score": 0.48,
    "career_progression_score": 0.79,
    "technical_skills": [
      "Sales Core",
      "Account Executive Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Very balanced workload and exciting technical challenges. Leadership respects work-life boundaries."
  },
  {
    "employee_id": "EMP-1018",
    "department": "Accounting",
    "job_level": "Senior",
    "role": "Accountant",
    "communication_patterns": "Exhibits communication style typical of a CorporateCompliance persona.",
    "persona_name": "Vikram Malhotra",
    "tenure_months": 59.0,
    "salary": 161399.0,
    "performance_score": 0.89,
    "satisfaction_score": 0.87,
    "workload_score": 0.37,
    "team_sentiment": 0.84,
    "project_completion_rate": 0.89,
    "overtime_hours": 1.8,
    "training_participation": 0.77,
    "collaboration_score": 0.81,
    "email_sentiment": 0.85,
    "slack_activity": 0.67,
    "meeting_participation": 0.49,
    "goal_achievement_rate": 0.89,
    "stress_level": 0.11,
    "role_complexity_score": 0.5,
    "career_progression_score": 0.81,
    "technical_skills": [
      "Accounting Core",
      "Accountant Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Excellent compensation, modern toolchain, and transparent communication across all executive channels."
  },
  {
    "employee_id": "EMP-1019",
    "department": "Software Engineering",
    "job_level": "Lead",
    "role": "Principal Engineer",
    "communication_patterns": "Exhibits communication style typical of a DistributedSystems persona.",
    "persona_name": "Grace Hopper",
    "tenure_months": 54.0,
    "salary": 145714.0,
    "performance_score": 0.93,
    "satisfaction_score": 0.92,
    "workload_score": 0.46,
    "team_sentiment": 0.9,
    "project_completion_rate": 0.94,
    "overtime_hours": 3.9,
    "training_participation": 0.86,
    "collaboration_score": 0.88,
    "email_sentiment": 0.92,
    "slack_activity": 0.76,
    "meeting_participation": 0.6,
    "goal_achievement_rate": 0.93,
    "stress_level": 0.18,
    "role_complexity_score": 0.63,
    "career_progression_score": 0.88,
    "technical_skills": [
      "Software Engineering Core",
      "Principal Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Love the team environment and autonomy given to individual contributors. Very rewarding place to work."
  },
  {
    "employee_id": "EMP-1020",
    "department": "Customer Service",
    "job_level": "Mid",
    "role": "Support Engineer",
    "communication_patterns": "Exhibits communication style typical of a Tier-3Escalations persona.",
    "persona_name": "Tariq Thorne",
    "tenure_months": 41.0,
    "salary": 161398.0,
    "performance_score": 0.86,
    "satisfaction_score": 0.84,
    "workload_score": 0.32,
    "team_sentiment": 0.81,
    "project_completion_rate": 0.86,
    "overtime_hours": 0.6,
    "training_participation": 0.72,
    "collaboration_score": 0.77,
    "email_sentiment": 0.82,
    "slack_activity": 0.62,
    "meeting_participation": 0.43,
    "goal_achievement_rate": 0.86,
    "stress_level": 0.07,
    "role_complexity_score": 0.43,
    "career_progression_score": 0.77,
    "technical_skills": [
      "Customer Service Core",
      "Support Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Strong mentorship, clear progression goals, and reasonable project deadlines without weekend fire drills."
  },
  {
    "employee_id": "EMP-1021",
    "department": "Training",
    "job_level": "Mid",
    "role": "Instructional Designer",
    "communication_patterns": "Exhibits communication style typical of a LearningPrograms persona.",
    "persona_name": "Hannah Abbott",
    "tenure_months": 43.0,
    "salary": 118483.0,
    "performance_score": 0.81,
    "satisfaction_score": 0.65,
    "workload_score": 0.68,
    "team_sentiment": 0.67,
    "project_completion_rate": 0.81,
    "overtime_hours": 19.1,
    "training_participation": 0.53,
    "collaboration_score": 0.65,
    "email_sentiment": 0.62,
    "slack_activity": 0.6,
    "meeting_participation": 0.65,
    "goal_achievement_rate": 0.78,
    "stress_level": 0.59,
    "role_complexity_score": 0.68,
    "career_progression_score": 0.55,
    "technical_skills": [
      "Training Core",
      "Instructional Designer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Overall solid work environment, though cross-functional communication between teams can occasionally drag."
  },
  {
    "employee_id": "EMP-1022",
    "department": "Technology",
    "job_level": "Entry",
    "role": "QA Analyst",
    "communication_patterns": "Exhibits communication style typical of a AutomatedTesting persona.",
    "persona_name": "Lucas Silva",
    "tenure_months": 17.0,
    "salary": 85305.0,
    "performance_score": 0.71,
    "satisfaction_score": 0.56,
    "workload_score": 0.59,
    "team_sentiment": 0.56,
    "project_completion_rate": 0.71,
    "overtime_hours": 12.6,
    "training_participation": 0.36,
    "collaboration_score": 0.51,
    "email_sentiment": 0.51,
    "slack_activity": 0.46,
    "meeting_participation": 0.51,
    "goal_achievement_rate": 0.69,
    "stress_level": 0.46,
    "role_complexity_score": 0.51,
    "career_progression_score": 0.41,
    "technical_skills": [
      "Technology Core",
      "QA Analyst Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Good benefits and friendly peers, but meeting load has increased recently and sprint planning is sometimes rushed."
  },
  {
    "employee_id": "EMP-1023",
    "department": "Human Resources",
    "job_level": "Senior",
    "role": "Recruitment Lead",
    "communication_patterns": "Exhibits communication style typical of a ExecutiveHiring persona.",
    "persona_name": "Maya Lin",
    "tenure_months": 12.0,
    "salary": 113893.0,
    "performance_score": 0.74,
    "satisfaction_score": 0.59,
    "workload_score": 0.62,
    "team_sentiment": 0.59,
    "project_completion_rate": 0.74,
    "overtime_hours": 14.5,
    "training_participation": 0.41,
    "collaboration_score": 0.55,
    "email_sentiment": 0.54,
    "slack_activity": 0.5,
    "meeting_participation": 0.55,
    "goal_achievement_rate": 0.72,
    "stress_level": 0.5,
    "role_complexity_score": 0.56,
    "career_progression_score": 0.45,
    "technical_skills": [
      "Human Resources Core",
      "Recruitment Lead Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Decent compensation and interesting projects, but roadmap priorities shift frequently causing slight friction."
  },
  {
    "employee_id": "EMP-1024",
    "department": "Finance",
    "job_level": "Mid",
    "role": "Risk Analyst",
    "communication_patterns": "Exhibits communication style typical of a PortfolioAnalysis persona.",
    "persona_name": "Gabriel Santos",
    "tenure_months": 27.0,
    "salary": 111555.0,
    "performance_score": 0.79,
    "satisfaction_score": 0.64,
    "workload_score": 0.67,
    "team_sentiment": 0.65,
    "project_completion_rate": 0.79,
    "overtime_hours": 18.2,
    "training_participation": 0.51,
    "collaboration_score": 0.63,
    "email_sentiment": 0.6,
    "slack_activity": 0.58,
    "meeting_participation": 0.63,
    "goal_achievement_rate": 0.77,
    "stress_level": 0.57,
    "role_complexity_score": 0.66,
    "career_progression_score": 0.53,
    "technical_skills": [
      "Finance Core",
      "Risk Analyst Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Workload is manageable most of the time, but quarterly deadlines create temporary stress spikes."
  },
  {
    "employee_id": "EMP-1025",
    "department": "Sales & Marketing",
    "job_level": "Lead",
    "role": "Growth Marketing Director",
    "communication_patterns": "Exhibits communication style typical of a Acquisition persona.",
    "persona_name": "Zoe Kravitz",
    "tenure_months": 42.0,
    "salary": 115474.0,
    "performance_score": 0.87,
    "satisfaction_score": 0.71,
    "workload_score": 0.74,
    "team_sentiment": 0.74,
    "project_completion_rate": 0.87,
    "overtime_hours": 23.5,
    "training_participation": 0.64,
    "collaboration_score": 0.74,
    "email_sentiment": 0.69,
    "slack_activity": 0.69,
    "meeting_participation": 0.74,
    "goal_achievement_rate": 0.84,
    "stress_level": 0.67,
    "role_complexity_score": 0.79,
    "career_progression_score": 0.64,
    "technical_skills": [
      "Sales & Marketing Core",
      "Growth Marketing Director Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Overall solid work environment, though cross-functional communication between teams can occasionally drag."
  },
  {
    "employee_id": "EMP-1026",
    "department": "Operations",
    "job_level": "Mid",
    "role": "Logistics Coordinator",
    "communication_patterns": "Exhibits communication style typical of a Fulfillment persona.",
    "persona_name": "Benjamin Hayes",
    "tenure_months": 12.0,
    "salary": 99828.0,
    "performance_score": 0.86,
    "satisfaction_score": 0.7,
    "workload_score": 0.73,
    "team_sentiment": 0.72,
    "project_completion_rate": 0.86,
    "overtime_hours": 22.4,
    "training_participation": 0.61,
    "collaboration_score": 0.72,
    "email_sentiment": 0.67,
    "slack_activity": 0.67,
    "meeting_participation": 0.72,
    "goal_achievement_rate": 0.83,
    "stress_level": 0.65,
    "role_complexity_score": 0.76,
    "career_progression_score": 0.62,
    "technical_skills": [
      "Operations Core",
      "Logistics Coordinator Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Good benefits and friendly peers, but meeting load has increased recently and sprint planning is sometimes rushed."
  },
  {
    "employee_id": "EMP-1027",
    "department": "Software Engineering",
    "job_level": "Senior",
    "role": "Backend Engineer",
    "communication_patterns": "Exhibits communication style typical of a APIServices persona.",
    "persona_name": "Nadia Chernova",
    "tenure_months": 14.0,
    "salary": 124069.0,
    "performance_score": 0.76,
    "satisfaction_score": 0.6,
    "workload_score": 0.63,
    "team_sentiment": 0.61,
    "project_completion_rate": 0.76,
    "overtime_hours": 15.7,
    "training_participation": 0.44,
    "collaboration_score": 0.58,
    "email_sentiment": 0.56,
    "slack_activity": 0.53,
    "meeting_participation": 0.58,
    "goal_achievement_rate": 0.73,
    "stress_level": 0.52,
    "role_complexity_score": 0.59,
    "career_progression_score": 0.48,
    "technical_skills": [
      "Software Engineering Core",
      "Backend Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Decent compensation and interesting projects, but roadmap priorities shift frequently causing slight friction."
  },
  {
    "employee_id": "EMP-1028",
    "department": "IT/IS",
    "job_level": "Senior",
    "role": "Security Analyst",
    "communication_patterns": "Exhibits communication style typical of a InfoSec&Compliance persona.",
    "persona_name": "Ethan Hunt",
    "tenure_months": 27.0,
    "salary": 75139.0,
    "performance_score": 0.78,
    "satisfaction_score": 0.62,
    "workload_score": 0.65,
    "team_sentiment": 0.64,
    "project_completion_rate": 0.78,
    "overtime_hours": 17.1,
    "training_participation": 0.48,
    "collaboration_score": 0.61,
    "email_sentiment": 0.59,
    "slack_activity": 0.56,
    "meeting_participation": 0.61,
    "goal_achievement_rate": 0.75,
    "stress_level": 0.55,
    "role_complexity_score": 0.63,
    "career_progression_score": 0.51,
    "technical_skills": [
      "IT/IS Core",
      "Security Analyst Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Workload is manageable most of the time, but quarterly deadlines create temporary stress spikes."
  },
  {
    "employee_id": "EMP-1029",
    "department": "Analytics",
    "job_level": "Lead",
    "role": "Analytics Manager",
    "communication_patterns": "Exhibits communication style typical of a BusinessIntelligence persona.",
    "persona_name": "Isabella Ross",
    "tenure_months": 9.0,
    "salary": 112241.0,
    "performance_score": 0.83,
    "satisfaction_score": 0.67,
    "workload_score": 0.7,
    "team_sentiment": 0.7,
    "project_completion_rate": 0.83,
    "overtime_hours": 20.7,
    "training_participation": 0.57,
    "collaboration_score": 0.68,
    "email_sentiment": 0.65,
    "slack_activity": 0.63,
    "meeting_participation": 0.68,
    "goal_achievement_rate": 0.8,
    "stress_level": 0.62,
    "role_complexity_score": 0.72,
    "career_progression_score": 0.58,
    "technical_skills": [
      "Analytics Core",
      "Analytics Manager Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Overall solid work environment, though cross-functional communication between teams can occasionally drag."
  },
  {
    "employee_id": "EMP-1030",
    "department": "Software Engineering",
    "job_level": "Mid",
    "role": "Mobile Engineer",
    "communication_patterns": "Exhibits communication style typical of a iOS&Android persona.",
    "persona_name": "Noah Taylor",
    "tenure_months": 29.0,
    "salary": 94533.0,
    "performance_score": 0.86,
    "satisfaction_score": 0.7,
    "workload_score": 0.73,
    "team_sentiment": 0.72,
    "project_completion_rate": 0.86,
    "overtime_hours": 22.4,
    "training_participation": 0.61,
    "collaboration_score": 0.72,
    "email_sentiment": 0.67,
    "slack_activity": 0.67,
    "meeting_participation": 0.72,
    "goal_achievement_rate": 0.83,
    "stress_level": 0.65,
    "role_complexity_score": 0.76,
    "career_progression_score": 0.62,
    "technical_skills": [
      "Software Engineering Core",
      "Mobile Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Good benefits and friendly peers, but meeting load has increased recently and sprint planning is sometimes rushed."
  },
  {
    "employee_id": "EMP-1031",
    "department": "Technology",
    "job_level": "Mid",
    "role": "Database Administrator",
    "communication_patterns": "Exhibits communication style typical of a DatabaseReliability persona.",
    "persona_name": "Ananya Roy",
    "tenure_months": 45.0,
    "salary": 108693.0,
    "performance_score": 0.82,
    "satisfaction_score": 0.66,
    "workload_score": 0.69,
    "team_sentiment": 0.68,
    "project_completion_rate": 0.82,
    "overtime_hours": 19.7,
    "training_participation": 0.54,
    "collaboration_score": 0.66,
    "email_sentiment": 0.63,
    "slack_activity": 0.61,
    "meeting_participation": 0.66,
    "goal_achievement_rate": 0.79,
    "stress_level": 0.6,
    "role_complexity_score": 0.69,
    "career_progression_score": 0.56,
    "technical_skills": [
      "Technology Core",
      "Database Administrator Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Decent compensation and interesting projects, but roadmap priorities shift frequently causing slight friction."
  },
  {
    "employee_id": "EMP-1032",
    "department": "Sales",
    "job_level": "Senior",
    "role": "Senior Account Manager",
    "communication_patterns": "Exhibits communication style typical of a KeyAccounts persona.",
    "persona_name": "Oliver Queen",
    "tenure_months": 26.0,
    "salary": 123970.0,
    "performance_score": 0.75,
    "satisfaction_score": 0.6,
    "workload_score": 0.63,
    "team_sentiment": 0.61,
    "project_completion_rate": 0.75,
    "overtime_hours": 15.4,
    "training_participation": 0.44,
    "collaboration_score": 0.57,
    "email_sentiment": 0.56,
    "slack_activity": 0.52,
    "meeting_participation": 0.57,
    "goal_achievement_rate": 0.73,
    "stress_level": 0.52,
    "role_complexity_score": 0.59,
    "career_progression_score": 0.47,
    "technical_skills": [
      "Sales Core",
      "Senior Account Manager Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Workload is manageable most of the time, but quarterly deadlines create temporary stress spikes."
  },
  {
    "employee_id": "EMP-1033",
    "department": "Human Resources",
    "job_level": "Entry",
    "role": "HR Coordinator",
    "communication_patterns": "Exhibits communication style typical of a Onboarding persona.",
    "persona_name": "Emma Watson",
    "tenure_months": 31.0,
    "salary": 80967.0,
    "performance_score": 0.85,
    "satisfaction_score": 0.7,
    "workload_score": 0.73,
    "team_sentiment": 0.72,
    "project_completion_rate": 0.85,
    "overtime_hours": 22.3,
    "training_participation": 0.61,
    "collaboration_score": 0.71,
    "email_sentiment": 0.67,
    "slack_activity": 0.66,
    "meeting_participation": 0.71,
    "goal_achievement_rate": 0.83,
    "stress_level": 0.65,
    "role_complexity_score": 0.76,
    "career_progression_score": 0.61,
    "technical_skills": [
      "Human Resources Core",
      "HR Coordinator Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Overall solid work environment, though cross-functional communication between teams can occasionally drag."
  },
  {
    "employee_id": "EMP-1034",
    "department": "Operations",
    "job_level": "Senior",
    "role": "Process Engineer",
    "communication_patterns": "Exhibits communication style typical of a LeanAutomation persona.",
    "persona_name": "Mateo Fernandez",
    "tenure_months": 28.0,
    "salary": 93572.0,
    "performance_score": 0.74,
    "satisfaction_score": 0.59,
    "workload_score": 0.62,
    "team_sentiment": 0.6,
    "project_completion_rate": 0.74,
    "overtime_hours": 15.0,
    "training_participation": 0.42,
    "collaboration_score": 0.56,
    "email_sentiment": 0.55,
    "slack_activity": 0.51,
    "meeting_participation": 0.56,
    "goal_achievement_rate": 0.72,
    "stress_level": 0.51,
    "role_complexity_score": 0.57,
    "career_progression_score": 0.46,
    "technical_skills": [
      "Operations Core",
      "Process Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Good benefits and friendly peers, but meeting load has increased recently and sprint planning is sometimes rushed."
  },
  {
    "employee_id": "EMP-1035",
    "department": "Research & Development",
    "job_level": "Lead",
    "role": "Senior Research Lead",
    "communication_patterns": "Exhibits communication style typical of a DeepLearning persona.",
    "persona_name": "Kavita Nair",
    "tenure_months": 7.0,
    "salary": 71681.0,
    "performance_score": 0.56,
    "satisfaction_score": 0.31,
    "workload_score": 0.78,
    "team_sentiment": 0.31,
    "project_completion_rate": 0.56,
    "overtime_hours": 30.7,
    "training_participation": 0.11,
    "collaboration_score": 0.31,
    "email_sentiment": 0.26,
    "slack_activity": 0.26,
    "meeting_participation": 0.66,
    "goal_achievement_rate": 0.51,
    "stress_level": 0.76,
    "role_complexity_score": 0.61,
    "career_progression_score": 0.21,
    "technical_skills": [
      "Research & Development Core",
      "Senior Research Lead Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Career progression feels opaque and compensation reviews have not kept up with expanded project scope."
  },
  {
    "employee_id": "EMP-1036",
    "department": "Customer Service",
    "job_level": "Manager",
    "role": "Customer Support Director",
    "communication_patterns": "Exhibits communication style typical of a ServiceOps persona.",
    "persona_name": "Samuel Jackson",
    "tenure_months": 15.0,
    "salary": 65833.0,
    "performance_score": 0.64,
    "satisfaction_score": 0.38,
    "workload_score": 0.83,
    "team_sentiment": 0.39,
    "project_completion_rate": 0.63,
    "overtime_hours": 38.2,
    "training_participation": 0.19,
    "collaboration_score": 0.39,
    "email_sentiment": 0.34,
    "slack_activity": 0.34,
    "meeting_participation": 0.76,
    "goal_achievement_rate": 0.58,
    "stress_level": 0.82,
    "role_complexity_score": 0.71,
    "career_progression_score": 0.29,
    "technical_skills": [
      "Customer Service Core",
      "Customer Support Director Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Too many context switches and unrealistic delivery expectations from stakeholders without adequate support."
  },
  {
    "employee_id": "EMP-1037",
    "department": "Sales & Marketing",
    "job_level": "Senior",
    "role": "Brand Strategist",
    "communication_patterns": "Exhibits communication style typical of a MarketPositioning persona.",
    "persona_name": "Jessica Alba",
    "tenure_months": 11.0,
    "salary": 89317.0,
    "performance_score": 0.7,
    "satisfaction_score": 0.43,
    "workload_score": 0.87,
    "team_sentiment": 0.45,
    "project_completion_rate": 0.67,
    "overtime_hours": 43.1,
    "training_participation": 0.25,
    "collaboration_score": 0.45,
    "email_sentiment": 0.4,
    "slack_activity": 0.4,
    "meeting_participation": 0.82,
    "goal_achievement_rate": 0.63,
    "stress_level": 0.86,
    "role_complexity_score": 0.78,
    "career_progression_score": 0.35,
    "technical_skills": [
      "Sales & Marketing Core",
      "Brand Strategist Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "High overtime hours and heavy on-call load are starting to impact personal life and team morale."
  },
  {
    "employee_id": "EMP-1038",
    "department": "Finance",
    "job_level": "Lead",
    "role": "Finance Director",
    "communication_patterns": "Exhibits communication style typical of a CapitalAllocation persona.",
    "persona_name": "Leo Tolstoy",
    "tenure_months": 21.0,
    "salary": 94703.0,
    "performance_score": 0.74,
    "satisfaction_score": 0.47,
    "workload_score": 0.89,
    "team_sentiment": 0.49,
    "project_completion_rate": 0.71,
    "overtime_hours": 47.0,
    "training_participation": 0.29,
    "collaboration_score": 0.49,
    "email_sentiment": 0.44,
    "slack_activity": 0.44,
    "meeting_participation": 0.87,
    "goal_achievement_rate": 0.67,
    "stress_level": 0.89,
    "role_complexity_score": 0.84,
    "career_progression_score": 0.39,
    "technical_skills": [
      "Finance Core",
      "Finance Director Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Lack of adequate staffing on key initiatives has caused persistent bottlenecking and elevated fatigue."
  },
  {
    "employee_id": "EMP-1039",
    "department": "Software Engineering",
    "job_level": "Entry",
    "role": "Associate Engineer",
    "communication_patterns": "Exhibits communication style typical of a BackendTools persona.",
    "persona_name": "Devon Price",
    "tenure_months": 7.0,
    "salary": 92161.0,
    "performance_score": 0.63,
    "satisfaction_score": 0.37,
    "workload_score": 0.83,
    "team_sentiment": 0.38,
    "project_completion_rate": 0.62,
    "overtime_hours": 36.9,
    "training_participation": 0.18,
    "collaboration_score": 0.38,
    "email_sentiment": 0.33,
    "slack_activity": 0.33,
    "meeting_participation": 0.74,
    "goal_achievement_rate": 0.57,
    "stress_level": 0.81,
    "role_complexity_score": 0.7,
    "career_progression_score": 0.28,
    "technical_skills": [
      "Software Engineering Core",
      "Associate Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Career progression feels opaque and compensation reviews have not kept up with expanded project scope."
  },
  {
    "employee_id": "EMP-1040",
    "department": "IT/IS",
    "job_level": "Manager",
    "role": "IT Infrastructure Director",
    "communication_patterns": "Exhibits communication style typical of a EnterpriseIT persona.",
    "persona_name": "Nadine Labaki",
    "tenure_months": 15.0,
    "salary": 84681.0,
    "performance_score": 0.66,
    "satisfaction_score": 0.4,
    "workload_score": 0.85,
    "team_sentiment": 0.41,
    "project_completion_rate": 0.64,
    "overtime_hours": 39.8,
    "training_participation": 0.21,
    "collaboration_score": 0.41,
    "email_sentiment": 0.36,
    "slack_activity": 0.36,
    "meeting_participation": 0.78,
    "goal_achievement_rate": 0.6,
    "stress_level": 0.83,
    "role_complexity_score": 0.74,
    "career_progression_score": 0.31,
    "technical_skills": [
      "IT/IS Core",
      "IT Infrastructure Director Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Too many context switches and unrealistic delivery expectations from stakeholders without adequate support."
  },
  {
    "employee_id": "EMP-1041",
    "department": "Technology",
    "job_level": "Senior",
    "role": "Reliability Engineer",
    "communication_patterns": "Exhibits communication style typical of a Observability persona.",
    "persona_name": "Zachary Levi",
    "tenure_months": 12.0,
    "salary": 71590.0,
    "performance_score": 0.63,
    "satisfaction_score": 0.37,
    "workload_score": 0.83,
    "team_sentiment": 0.38,
    "project_completion_rate": 0.62,
    "overtime_hours": 37.3,
    "training_participation": 0.18,
    "collaboration_score": 0.38,
    "email_sentiment": 0.33,
    "slack_activity": 0.33,
    "meeting_participation": 0.74,
    "goal_achievement_rate": 0.57,
    "stress_level": 0.81,
    "role_complexity_score": 0.7,
    "career_progression_score": 0.28,
    "technical_skills": [
      "Technology Core",
      "Reliability Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "High overtime hours and heavy on-call load are starting to impact personal life and team morale."
  },
  {
    "employee_id": "EMP-1042",
    "department": "Analytics",
    "job_level": "Senior",
    "role": "Machine Learning Engineer",
    "communication_patterns": "Exhibits communication style typical of a NLPWorkflows persona.",
    "persona_name": "Siddharth Gupta",
    "tenure_months": 6.0,
    "salary": 94752.0,
    "performance_score": 0.6,
    "satisfaction_score": 0.35,
    "workload_score": 0.81,
    "team_sentiment": 0.35,
    "project_completion_rate": 0.59,
    "overtime_hours": 34.5,
    "training_participation": 0.15,
    "collaboration_score": 0.35,
    "email_sentiment": 0.3,
    "slack_activity": 0.3,
    "meeting_participation": 0.71,
    "goal_achievement_rate": 0.55,
    "stress_level": 0.79,
    "role_complexity_score": 0.66,
    "career_progression_score": 0.25,
    "technical_skills": [
      "Analytics Core",
      "Machine Learning Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Lack of adequate staffing on key initiatives has caused persistent bottlenecking and elevated fatigue."
  },
  {
    "employee_id": "EMP-1043",
    "department": "Customer Service",
    "job_level": "Entry",
    "role": "Customer Success Associate",
    "communication_patterns": "Exhibits communication style typical of a ClientCare persona.",
    "persona_name": "Audrey Tautou",
    "tenure_months": 12.0,
    "salary": 75795.0,
    "performance_score": 0.62,
    "satisfaction_score": 0.37,
    "workload_score": 0.82,
    "team_sentiment": 0.37,
    "project_completion_rate": 0.61,
    "overtime_hours": 36.7,
    "training_participation": 0.17,
    "collaboration_score": 0.37,
    "email_sentiment": 0.32,
    "slack_activity": 0.32,
    "meeting_participation": 0.74,
    "goal_achievement_rate": 0.57,
    "stress_level": 0.81,
    "role_complexity_score": 0.69,
    "career_progression_score": 0.27,
    "technical_skills": [
      "Customer Service Core",
      "Customer Success Associate Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Career progression feels opaque and compensation reviews have not kept up with expanded project scope."
  },
  {
    "employee_id": "EMP-1044",
    "department": "Operations",
    "job_level": "Lead",
    "role": "Facilities Director",
    "communication_patterns": "Exhibits communication style typical of a PhysicalInfrastructure persona.",
    "persona_name": "Keanu Reeves",
    "tenure_months": 10.0,
    "salary": 74148.0,
    "performance_score": 0.57,
    "satisfaction_score": 0.32,
    "workload_score": 0.79,
    "team_sentiment": 0.32,
    "project_completion_rate": 0.57,
    "overtime_hours": 32.1,
    "training_participation": 0.12,
    "collaboration_score": 0.32,
    "email_sentiment": 0.27,
    "slack_activity": 0.27,
    "meeting_participation": 0.68,
    "goal_achievement_rate": 0.52,
    "stress_level": 0.77,
    "role_complexity_score": 0.63,
    "career_progression_score": 0.22,
    "technical_skills": [
      "Operations Core",
      "Facilities Director Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Too many context switches and unrealistic delivery expectations from stakeholders without adequate support."
  },
  {
    "employee_id": "EMP-1045",
    "department": "Software Engineering",
    "job_level": "Senior",
    "role": "Security Engineer",
    "communication_patterns": "Exhibits communication style typical of a AppSec persona.",
    "persona_name": "Yuki Tanaka",
    "tenure_months": 7.0,
    "salary": 69100.0,
    "performance_score": 0.57,
    "satisfaction_score": 0.2,
    "workload_score": 0.98,
    "team_sentiment": 0.27,
    "project_completion_rate": 0.52,
    "overtime_hours": 65.4,
    "training_participation": 0.13,
    "collaboration_score": 0.28,
    "email_sentiment": 0.18,
    "slack_activity": 0.23,
    "meeting_participation": 0.92,
    "goal_achievement_rate": 0.47,
    "stress_level": 0.98,
    "role_complexity_score": 0.91,
    "career_progression_score": 0.18,
    "technical_skills": [
      "Software Engineering Core",
      "Security Engineer Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Severe burnout from sustained 60+ hour work weeks and zero acknowledgment of extra effort. High turnover risk."
  },
  {
    "employee_id": "EMP-1046",
    "department": "Sales",
    "job_level": "Mid",
    "role": "Sales Development Representative",
    "communication_patterns": "Exhibits communication style typical of a OutboundPipeline persona.",
    "persona_name": "Oscar Isaac",
    "tenure_months": 15.0,
    "salary": 61558.0,
    "performance_score": 0.6,
    "satisfaction_score": 0.22,
    "workload_score": 0.99,
    "team_sentiment": 0.3,
    "project_completion_rate": 0.55,
    "overtime_hours": 67.8,
    "training_participation": 0.15,
    "collaboration_score": 0.3,
    "email_sentiment": 0.2,
    "slack_activity": 0.25,
    "meeting_participation": 0.95,
    "goal_achievement_rate": 0.5,
    "stress_level": 0.99,
    "role_complexity_score": 0.95,
    "career_progression_score": 0.2,
    "technical_skills": [
      "Sales Core",
      "Sales Development Representative Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Toxic workload distribution, unmanageable expectations, and unresponsive management. Actively seeking external roles."
  },
  {
    "employee_id": "EMP-1047",
    "department": "Research & Development",
    "job_level": "Entry",
    "role": "Research Associate",
    "communication_patterns": "Exhibits communication style typical of a ExperimentalR&D persona.",
    "persona_name": "Mei Ling",
    "tenure_months": 9.0,
    "salary": 70549.0,
    "performance_score": 0.56,
    "satisfaction_score": 0.19,
    "workload_score": 0.97,
    "team_sentiment": 0.26,
    "project_completion_rate": 0.51,
    "overtime_hours": 64.5,
    "training_participation": 0.12,
    "collaboration_score": 0.27,
    "email_sentiment": 0.17,
    "slack_activity": 0.22,
    "meeting_participation": 0.91,
    "goal_achievement_rate": 0.46,
    "stress_level": 0.97,
    "role_complexity_score": 0.9,
    "career_progression_score": 0.17,
    "technical_skills": [
      "Research & Development Core",
      "Research Associate Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Extreme exhaustion and completely unsustainable deadlines. Team morale has collapsed due to chronic understaffing."
  },
  {
    "employee_id": "EMP-1048",
    "department": "Human Resources",
    "job_level": "Mid",
    "role": "People Operations Partner",
    "communication_patterns": "Exhibits communication style typical of a EmployeeRelations persona.",
    "persona_name": "Dante Alighieri",
    "tenure_months": 11.0,
    "salary": 93023.0,
    "performance_score": 0.42,
    "satisfaction_score": 0.1,
    "workload_score": 0.91,
    "team_sentiment": 0.12,
    "project_completion_rate": 0.37,
    "overtime_hours": 53.8,
    "training_participation": 0.03,
    "collaboration_score": 0.17,
    "email_sentiment": 0.07,
    "slack_activity": 0.12,
    "meeting_participation": 0.77,
    "goal_achievement_rate": 0.32,
    "stress_level": 0.93,
    "role_complexity_score": 0.73,
    "career_progression_score": 0.07,
    "technical_skills": [
      "Human Resources Core",
      "People Operations Partner Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Constant fire-fighting, zero career advancement, and compensation far below market benchmarks. Disengaged."
  },
  {
    "employee_id": "EMP-1049",
    "department": "Accounting",
    "job_level": "Mid",
    "role": "Senior Auditor",
    "communication_patterns": "Exhibits communication style typical of a FinancialControls persona.",
    "persona_name": "Svetlana Ivanova",
    "tenure_months": 4.0,
    "salary": 70872.0,
    "performance_score": 0.4,
    "satisfaction_score": 0.08,
    "workload_score": 0.9,
    "team_sentiment": 0.1,
    "project_completion_rate": 0.35,
    "overtime_hours": 52.3,
    "training_participation": 0.02,
    "collaboration_score": 0.15,
    "email_sentiment": 0.05,
    "slack_activity": 0.1,
    "meeting_participation": 0.75,
    "goal_achievement_rate": 0.3,
    "stress_level": 0.92,
    "role_complexity_score": 0.7,
    "career_progression_score": 0.05,
    "technical_skills": [
      "Accounting Core",
      "Senior Auditor Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Severe burnout from sustained 60+ hour work weeks and zero acknowledgment of extra effort. High turnover risk."
  },
  {
    "employee_id": "EMP-1050",
    "department": "Technology",
    "job_level": "Senior",
    "role": "Solutions Architect",
    "communication_patterns": "Exhibits communication style typical of a PartnerIntegrations persona.",
    "persona_name": "Arthur Pendelton",
    "tenure_months": 14.0,
    "salary": 55426.0,
    "performance_score": 0.46,
    "satisfaction_score": 0.12,
    "workload_score": 0.93,
    "team_sentiment": 0.16,
    "project_completion_rate": 0.41,
    "overtime_hours": 56.8,
    "training_participation": 0.06,
    "collaboration_score": 0.2,
    "email_sentiment": 0.1,
    "slack_activity": 0.15,
    "meeting_participation": 0.81,
    "goal_achievement_rate": 0.36,
    "stress_level": 0.94,
    "role_complexity_score": 0.78,
    "career_progression_score": 0.1,
    "technical_skills": [
      "Technology Core",
      "Solutions Architect Methods"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Toxic workload distribution, unmanageable expectations, and unresponsive management. Actively seeking external roles."
  }
];
