import { EmployeePredictionRequest } from '../types/api';

export const SAMPLE_EMPLOYEES: EmployeePredictionRequest[] = [
  {
    "employee_id": "EMP-1001",
    "department": "Technology",
    "job_level": "Mid",
    "role": "Anonymous Employee",
    "communication_patterns": "Exhibits communication style typical of a QuietAchiever persona.",
    "persona_name": "QuietAchiever",
    "tenure_months": 52.0,
    "salary": 75126.0,
    "performance_score": 0.94,
    "satisfaction_score": 0.7,
    "workload_score": 0.33,
    "team_sentiment": 0.4,
    "project_completion_rate": 0.77,
    "overtime_hours": 20.4,
    "training_participation": 0.16,
    "collaboration_score": 0.32,
    "email_sentiment": 0.71,
    "slack_activity": 0.32,
    "meeting_participation": 0.32,
    "goal_achievement_rate": 0.94,
    "stress_level": 0.95,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.99,
    "technical_skills": [
      "Software Engineering",
      "System Architecture"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Great office with great people in Old Town Scottsdale. Great to work for a company that is really trying to improve the world (reduce carbon footprint, thrus..."
  },
  {
    "employee_id": "EMP-1002",
    "department": "Technology",
    "job_level": "Mid",
    "role": "Crew Member",
    "communication_patterns": "Exhibits communication style typical of a SteadyEddy persona.",
    "persona_name": "SteadyEddy",
    "tenure_months": 13.0,
    "salary": 84449.0,
    "performance_score": 0.75,
    "satisfaction_score": 0.96,
    "workload_score": 0.86,
    "team_sentiment": 0.85,
    "project_completion_rate": 0.79,
    "overtime_hours": 0.0,
    "training_participation": 0.06,
    "collaboration_score": 0.83,
    "email_sentiment": 0.96,
    "slack_activity": 0.83,
    "meeting_participation": 0.83,
    "goal_achievement_rate": 0.75,
    "stress_level": 0.08,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.63,
    "technical_skills": [
      "Software Engineering",
      "System Architecture"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "- Salary - Benefits - Historically: talented, friendly colleagues Nice and happy place to work A lot of moving parts."
  },
  {
    "employee_id": "EMP-1003",
    "department": "Technology",
    "job_level": "Entry",
    "role": "Senior Associate",
    "communication_patterns": "Exhibits communication style typical of a ChangeResistor persona.",
    "persona_name": "ChangeResistor",
    "tenure_months": 23.0,
    "salary": 41582.0,
    "performance_score": 0.68,
    "satisfaction_score": 0.22,
    "workload_score": 0.59,
    "team_sentiment": 0.75,
    "project_completion_rate": 0.55,
    "overtime_hours": 0.0,
    "training_participation": 0.14,
    "collaboration_score": 0.32,
    "email_sentiment": 0.22,
    "slack_activity": 0.32,
    "meeting_participation": 0.32,
    "goal_achievement_rate": 0.68,
    "stress_level": 1.0,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.52,
    "technical_skills": [
      "Software Engineering",
      "System Architecture"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Great Company Reinventing Itself Poor job satisfaction with poor middle management. well it is not always care Big company with lots of bureaycracy"
  },
  {
    "employee_id": "EMP-1004",
    "department": "Sales & Marketing",
    "job_level": "Mid",
    "role": "Support Worker",
    "communication_patterns": "Exhibits communication style typical of a StrugglingLearner persona.",
    "persona_name": "StrugglingLearner",
    "tenure_months": 75.0,
    "salary": 65611.0,
    "performance_score": 0.33,
    "satisfaction_score": 0.12,
    "workload_score": 0.79,
    "team_sentiment": 0.61,
    "project_completion_rate": 0.27,
    "overtime_hours": 0.0,
    "training_participation": 0.29,
    "collaboration_score": 0.23,
    "email_sentiment": 0.11,
    "slack_activity": 0.23,
    "meeting_participation": 0.23,
    "goal_achievement_rate": 0.33,
    "stress_level": 1.0,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.8,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "A fun and exciting place to work in the early days, now a bureaucratic, inefficent, and bloated company I'm not sure what to put here The company mis-leads i..."
  },
  {
    "employee_id": "EMP-1005",
    "department": "Sales & Marketing",
    "job_level": "Mid",
    "role": "Crew Member/Grill Cook",
    "communication_patterns": "Exhibits communication style typical of a NewEnthusiast persona.",
    "persona_name": "NewEnthusiast",
    "tenure_months": 87.0,
    "salary": 50512.0,
    "performance_score": 0.77,
    "satisfaction_score": 0.99,
    "workload_score": 0.42,
    "team_sentiment": 0.65,
    "project_completion_rate": 0.67,
    "overtime_hours": 5.7,
    "training_participation": 0.43,
    "collaboration_score": 0.65,
    "email_sentiment": 1.0,
    "slack_activity": 0.65,
    "meeting_participation": 0.65,
    "goal_achievement_rate": 0.77,
    "stress_level": 0.7,
    "role_complexity_score": 0.2,
    "career_progression_score": 1.0,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Company is passionate about keeping people safe and solving the world's most complex challenges. The employee creates his/her own objectives or is given a se..."
  },
  {
    "employee_id": "EMP-1006",
    "department": "Sales & Marketing",
    "job_level": "Mid",
    "role": "Anonymous Employee",
    "communication_patterns": "Exhibits communication style typical of a ChangeResistor persona.",
    "persona_name": "ChangeResistor",
    "tenure_months": 51.0,
    "salary": 43486.0,
    "performance_score": 0.61,
    "satisfaction_score": 0.62,
    "workload_score": 0.46,
    "team_sentiment": 0.6,
    "project_completion_rate": 0.49,
    "overtime_hours": 2.3,
    "training_participation": 0.06,
    "collaboration_score": 0.44,
    "email_sentiment": 0.61,
    "slack_activity": 0.44,
    "meeting_participation": 0.44,
    "goal_achievement_rate": 0.61,
    "stress_level": 1.0,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.6,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Excellent company to work for, except.... The 50% discount was great! Friendly work place Good benefits Excellent work life balance Embracing industry standa..."
  },
  {
    "employee_id": "EMP-1007",
    "department": "Customer Service",
    "job_level": "Senior",
    "role": "Senior Consultant",
    "communication_patterns": "Exhibits communication style typical of a 9-to-5Clockwatcher persona.",
    "persona_name": "9-to-5Clockwatcher",
    "tenure_months": 99.0,
    "salary": 32037.0,
    "performance_score": 0.61,
    "satisfaction_score": 0.9,
    "workload_score": 0.89,
    "team_sentiment": 0.58,
    "project_completion_rate": 0.69,
    "overtime_hours": 0.0,
    "training_participation": 0.03,
    "collaboration_score": 0.56,
    "email_sentiment": 0.88,
    "slack_activity": 0.56,
    "meeting_participation": 0.56,
    "goal_achievement_rate": 0.61,
    "stress_level": 0.03,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.76,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "The people and technology at Morgan are superb. food and snacks in the office. Even if you don't make it to the brass ring, you build great skills and amazin..."
  },
  {
    "employee_id": "EMP-1008",
    "department": "Customer Service",
    "job_level": "Manager",
    "role": "Branch Manager",
    "communication_patterns": "Exhibits communication style typical of a SteadyEddy persona.",
    "persona_name": "SteadyEddy",
    "tenure_months": 1.0,
    "salary": 30338.0,
    "performance_score": 0.76,
    "satisfaction_score": 0.72,
    "workload_score": 0.17,
    "team_sentiment": 0.59,
    "project_completion_rate": 0.61,
    "overtime_hours": 9.9,
    "training_participation": 0.09,
    "collaboration_score": 0.5,
    "email_sentiment": 0.71,
    "slack_activity": 0.5,
    "meeting_participation": 0.5,
    "goal_achievement_rate": 0.76,
    "stress_level": 1.0,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.58,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "fifty percent discount go big sometimes New hire from services companies spoiling the culture"
  },
  {
    "employee_id": "EMP-1009",
    "department": "Customer Service",
    "job_level": "Entry",
    "role": "Associate",
    "communication_patterns": "Exhibits communication style typical of a 9-to-5Clockwatcher persona.",
    "persona_name": "9-to-5Clockwatcher",
    "tenure_months": 67.0,
    "salary": 47321.0,
    "performance_score": 0.59,
    "satisfaction_score": 0.69,
    "workload_score": 0.47,
    "team_sentiment": 0.57,
    "project_completion_rate": 0.55,
    "overtime_hours": 5.9,
    "training_participation": 0.04,
    "collaboration_score": 0.42,
    "email_sentiment": 0.7,
    "slack_activity": 0.42,
    "meeting_participation": 0.42,
    "goal_achievement_rate": 0.59,
    "stress_level": 0.63,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.61,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Do not pretend to care. good food and nice pepole Don't  screw your career by joining this company especially if you are joing in IT developement or Support ..."
  },
  {
    "employee_id": "EMP-1010",
    "department": "Operations",
    "job_level": "Mid",
    "role": "Anonymous Employee",
    "communication_patterns": "Exhibits communication style typical of a 9-to-5Clockwatcher persona.",
    "persona_name": "9-to-5Clockwatcher",
    "tenure_months": 95.0,
    "salary": 34790.0,
    "performance_score": 0.72,
    "satisfaction_score": 0.58,
    "workload_score": 0.47,
    "team_sentiment": 0.67,
    "project_completion_rate": 0.63,
    "overtime_hours": 3.6,
    "training_participation": 0.04,
    "collaboration_score": 0.47,
    "email_sentiment": 0.58,
    "slack_activity": 0.47,
    "meeting_participation": 0.47,
    "goal_achievement_rate": 0.72,
    "stress_level": 0.75,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.8,
    "technical_skills": [
      "Domain Expertise",
      "Data Analysis"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Smart, talented people. Can do complete career changes moving from Distribution to Merchandising to Property Development, etc. Only downside I've seen so far..."
  },
  {
    "employee_id": "EMP-1011",
    "department": "Operations",
    "job_level": "Mid",
    "role": "Programmer Analyst",
    "communication_patterns": "Exhibits communication style typical of a SteadyEddy persona.",
    "persona_name": "SteadyEddy",
    "tenure_months": 9.0,
    "salary": 117409.0,
    "performance_score": 0.75,
    "satisfaction_score": 0.06,
    "workload_score": 0.8,
    "team_sentiment": 0.64,
    "project_completion_rate": 0.6,
    "overtime_hours": 0.0,
    "training_participation": 0.22,
    "collaboration_score": 0.23,
    "email_sentiment": 0.08,
    "slack_activity": 0.23,
    "meeting_participation": 0.23,
    "goal_achievement_rate": 0.75,
    "stress_level": 1.0,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.61,
    "technical_skills": [
      "Domain Expertise",
      "Data Analysis"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Overall still a great company to work for Management can\u2019t seem to see the bigger picture and tend to micromanage staff over the most ridiculous things. Too ..."
  },
  {
    "employee_id": "EMP-1012",
    "department": "Operations",
    "job_level": "Mid",
    "role": "Sales Executive",
    "communication_patterns": "Exhibits communication style typical of a 9-to-5Clockwatcher persona.",
    "persona_name": "9-to-5Clockwatcher",
    "tenure_months": 84.0,
    "salary": 124581.0,
    "performance_score": 0.56,
    "satisfaction_score": 0.23,
    "workload_score": 0.67,
    "team_sentiment": 0.86,
    "project_completion_rate": 0.45,
    "overtime_hours": 0.0,
    "training_participation": 0.05,
    "collaboration_score": 0.4,
    "email_sentiment": 0.22,
    "slack_activity": 0.4,
    "meeting_participation": 0.4,
    "goal_achievement_rate": 0.56,
    "stress_level": 0.99,
    "role_complexity_score": 1.0,
    "career_progression_score": 0.67,
    "technical_skills": [
      "Domain Expertise",
      "Data Analysis"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Food was sub optimal to keep costs low. I've listened to a few joiners complain of being mis-sold regarding staff benefits that only apply to those in the ad..."
  },
  {
    "employee_id": "EMP-1013",
    "department": "Finance",
    "job_level": "Manager",
    "role": "Audit Manager",
    "communication_patterns": "Exhibits communication style typical of a CorporateNavigator persona.",
    "persona_name": "CorporateNavigator",
    "tenure_months": 125.0,
    "salary": 28945.0,
    "performance_score": 0.84,
    "satisfaction_score": 0.34,
    "workload_score": 0.4,
    "team_sentiment": 0.73,
    "project_completion_rate": 0.67,
    "overtime_hours": 17.3,
    "training_participation": 0.17,
    "collaboration_score": 0.42,
    "email_sentiment": 0.36,
    "slack_activity": 0.42,
    "meeting_participation": 0.42,
    "goal_achievement_rate": 0.84,
    "stress_level": 1.0,
    "role_complexity_score": 0.2,
    "career_progression_score": 1.0,
    "technical_skills": [
      "Domain Expertise",
      "Data Analysis"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Quality of projects varies a lot. Management, sales targets, too many kpi factors No care for staff safety during pandemic."
  },
  {
    "employee_id": "EMP-1014",
    "department": "Finance",
    "job_level": "Mid",
    "role": "Anonymous Employee",
    "communication_patterns": "Exhibits communication style typical of a SeasonedExpert persona.",
    "persona_name": "SeasonedExpert",
    "tenure_months": 17.0,
    "salary": 81797.0,
    "performance_score": 0.82,
    "satisfaction_score": 0.65,
    "workload_score": 0.78,
    "team_sentiment": 0.75,
    "project_completion_rate": 0.78,
    "overtime_hours": 0.0,
    "training_participation": 0.18,
    "collaboration_score": 0.58,
    "email_sentiment": 0.68,
    "slack_activity": 0.58,
    "meeting_participation": 0.58,
    "goal_achievement_rate": 0.82,
    "stress_level": 0.4,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.64,
    "technical_skills": [
      "Domain Expertise",
      "Data Analysis"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "sales exec schedule freedom until the expectation of weekly large account acquisitions aren't realized can't say anything bad about the company, but it is no..."
  },
  {
    "employee_id": "EMP-1015",
    "department": "Finance",
    "job_level": "Mid",
    "role": "Anonymous Employee",
    "communication_patterns": "Exhibits communication style typical of a SteadyEddy persona.",
    "persona_name": "SteadyEddy",
    "tenure_months": 38.0,
    "salary": 106964.0,
    "performance_score": 0.74,
    "satisfaction_score": 0.75,
    "workload_score": 0.5,
    "team_sentiment": 0.31,
    "project_completion_rate": 0.66,
    "overtime_hours": 0.0,
    "training_participation": 0.26,
    "collaboration_score": 0.25,
    "email_sentiment": 0.73,
    "slack_activity": 0.25,
    "meeting_participation": 0.25,
    "goal_achievement_rate": 0.74,
    "stress_level": 0.66,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.73,
    "technical_skills": [
      "Domain Expertise",
      "Data Analysis"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Brand recognition makes sales easier (walk-ins). Some projects provide work from home option."
  },
  {
    "employee_id": "EMP-1016",
    "department": "HR",
    "job_level": "Manager",
    "role": "Engagement Manager",
    "communication_patterns": "Exhibits communication style typical of a SteadyEddy persona.",
    "persona_name": "SteadyEddy",
    "tenure_months": 91.0,
    "salary": 48970.0,
    "performance_score": 0.78,
    "satisfaction_score": 0.51,
    "workload_score": 0.9,
    "team_sentiment": 0.66,
    "project_completion_rate": 0.73,
    "overtime_hours": 0.0,
    "training_participation": 0.25,
    "collaboration_score": 0.47,
    "email_sentiment": 0.53,
    "slack_activity": 0.47,
    "meeting_participation": 0.47,
    "goal_achievement_rate": 0.78,
    "stress_level": 0.48,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.97,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "The ups and downs of tech recruiting. Great devemopent and progression opportunities\r Full of driven, talented people\r Access to high quality technical resou..."
  },
  {
    "employee_id": "EMP-1017",
    "department": "HR",
    "job_level": "Lead",
    "role": "Director",
    "communication_patterns": "Exhibits communication style typical of a 9-to-5Clockwatcher persona.",
    "persona_name": "9-to-5Clockwatcher",
    "tenure_months": 4.0,
    "salary": 29554.0,
    "performance_score": 0.65,
    "satisfaction_score": 0.78,
    "workload_score": 0.45,
    "team_sentiment": 0.52,
    "project_completion_rate": 0.59,
    "overtime_hours": 7.7,
    "training_participation": 0.03,
    "collaboration_score": 0.48,
    "email_sentiment": 0.77,
    "slack_activity": 0.48,
    "meeting_participation": 0.48,
    "goal_achievement_rate": 0.65,
    "stress_level": 0.66,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.38,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "There are many benefits as well as work environment was fun. Good work environment and friendly people Fab employer, looks after service uses and staff Great..."
  },
  {
    "employee_id": "EMP-1018",
    "department": "HR",
    "job_level": "Manager",
    "role": "Manager",
    "communication_patterns": "Exhibits communication style typical of a NewEnthusiast persona.",
    "persona_name": "NewEnthusiast",
    "tenure_months": 25.0,
    "salary": 157058.0,
    "performance_score": 0.63,
    "satisfaction_score": 0.05,
    "workload_score": 0.59,
    "team_sentiment": 0.64,
    "project_completion_rate": 0.51,
    "overtime_hours": 0.0,
    "training_participation": 0.56,
    "collaboration_score": 0.22,
    "email_sentiment": 0.05,
    "slack_activity": 0.22,
    "meeting_participation": 0.22,
    "goal_achievement_rate": 0.63,
    "stress_level": 1.0,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.94,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Night Shifts if you don't like it otherwise its okay with many employee No increament after 1 year\r No recognition"
  },
  {
    "employee_id": "EMP-1019",
    "department": "Procurement",
    "job_level": "Mid",
    "role": "Unknown",
    "communication_patterns": "Exhibits communication style typical of a QuietAchiever persona.",
    "persona_name": "QuietAchiever",
    "tenure_months": 43.0,
    "salary": 85535.0,
    "performance_score": 0.75,
    "satisfaction_score": 0.98,
    "workload_score": 0.82,
    "team_sentiment": 0.69,
    "project_completion_rate": 0.76,
    "overtime_hours": 0.0,
    "training_participation": 0.53,
    "collaboration_score": 0.69,
    "email_sentiment": 1.0,
    "slack_activity": 0.69,
    "meeting_participation": 0.69,
    "goal_achievement_rate": 0.75,
    "stress_level": 0.18,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.85,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "comapny not very aware Great community, benefits and culture I find people to be very approachable."
  },
  {
    "employee_id": "EMP-1020",
    "department": "Procurement",
    "job_level": "Mid",
    "role": "Anonymous Employee",
    "communication_patterns": "Exhibits communication style typical of a NewEnthusiast persona.",
    "persona_name": "NewEnthusiast",
    "tenure_months": 67.0,
    "salary": 29852.0,
    "performance_score": 0.68,
    "satisfaction_score": 0.83,
    "workload_score": 0.8,
    "team_sentiment": 0.47,
    "project_completion_rate": 0.65,
    "overtime_hours": 0.0,
    "training_participation": 0.14,
    "collaboration_score": 0.42,
    "email_sentiment": 0.84,
    "slack_activity": 0.42,
    "meeting_participation": 0.42,
    "goal_achievement_rate": 0.68,
    "stress_level": 0.48,
    "role_complexity_score": 0.2,
    "career_progression_score": 1.0,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Awesome place for growth friendly colleagues, chose my own hours, nice location, Good place to have on your CV. The advantages of Hilton brand is a lot! bad ..."
  },
  {
    "employee_id": "EMP-1021",
    "department": "Procurement",
    "job_level": "Mid",
    "role": "PhD Student",
    "communication_patterns": "Exhibits communication style typical of a QuietAchiever persona.",
    "persona_name": "QuietAchiever",
    "tenure_months": 168.0,
    "salary": 36557.0,
    "performance_score": 0.74,
    "satisfaction_score": 0.87,
    "workload_score": 0.46,
    "team_sentiment": 0.62,
    "project_completion_rate": 0.66,
    "overtime_hours": 8.0,
    "training_participation": 0.24,
    "collaboration_score": 0.56,
    "email_sentiment": 0.86,
    "slack_activity": 0.56,
    "meeting_participation": 0.56,
    "goal_achievement_rate": 0.74,
    "stress_level": 0.68,
    "role_complexity_score": 0.2,
    "career_progression_score": 1.0,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Great pay, okay culture, mediocre values Excelent coworkers, innovation, competitives salaries, you could feel as a family Standards are simply that and the ..."
  },
  {
    "employee_id": "EMP-1022",
    "department": "Legal",
    "job_level": "Mid",
    "role": "Analyst",
    "communication_patterns": "Exhibits communication style typical of a CorporateNavigator persona.",
    "persona_name": "CorporateNavigator",
    "tenure_months": 113.0,
    "salary": 30289.0,
    "performance_score": 0.72,
    "satisfaction_score": 0.41,
    "workload_score": 0.94,
    "team_sentiment": 0.39,
    "project_completion_rate": 0.64,
    "overtime_hours": 0.0,
    "training_participation": 0.16,
    "collaboration_score": 0.23,
    "email_sentiment": 0.42,
    "slack_activity": 0.23,
    "meeting_participation": 0.23,
    "goal_achievement_rate": 0.72,
    "stress_level": 0.69,
    "role_complexity_score": 0.2,
    "career_progression_score": 1.0,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Literally, no one in a position of leadership within the company can offer any advice beyond cold calling (which no longer works). Salaries at the bottom in ..."
  },
  {
    "employee_id": "EMP-1023",
    "department": "Legal",
    "job_level": "Mid",
    "role": "Anonymous Employee",
    "communication_patterns": "Exhibits communication style typical of a 9-to-5Clockwatcher persona.",
    "persona_name": "9-to-5Clockwatcher",
    "tenure_months": 1.0,
    "salary": 29952.0,
    "performance_score": 0.56,
    "satisfaction_score": 0.6,
    "workload_score": 0.34,
    "team_sentiment": 0.87,
    "project_completion_rate": 0.48,
    "overtime_hours": 7.7,
    "training_participation": 0.04,
    "collaboration_score": 0.62,
    "email_sentiment": 0.59,
    "slack_activity": 0.62,
    "meeting_participation": 0.62,
    "goal_achievement_rate": 0.56,
    "stress_level": 0.87,
    "role_complexity_score": 0.2,
    "career_progression_score": 0.33,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "The leaders that come on Q&amp;A at least one of them should be laid off. Smart colleagues, best in class tools and infrastructure If commuting from SF, that..."
  },
  {
    "employee_id": "EMP-1024",
    "department": "Legal",
    "job_level": "Mid",
    "role": "nan",
    "communication_patterns": "Exhibits communication style typical of a 9-to-5Clockwatcher persona.",
    "persona_name": "9-to-5Clockwatcher",
    "tenure_months": 72.0,
    "salary": 55027.0,
    "performance_score": 0.35,
    "satisfaction_score": 0.43,
    "workload_score": 0.24,
    "team_sentiment": 0.67,
    "project_completion_rate": 0.28,
    "overtime_hours": 8.7,
    "training_participation": 0.05,
    "collaboration_score": 0.4,
    "email_sentiment": 0.42,
    "slack_activity": 0.4,
    "meeting_participation": 0.4,
    "goal_achievement_rate": 0.35,
    "stress_level": 1.0,
    "role_complexity_score": 0.23,
    "career_progression_score": 0.52,
    "technical_skills": [
      "Client Engagement",
      "CRM"
    ],
    "soft_skills": [
      "Cross-functional Collaboration",
      "Problem Solving",
      "Strategic Communication"
    ],
    "recent_feedback": "Perfect company for people growing poor work and lif balance As much as they are acquiring, the profitability can't stay forever."
  }
];
